### ISSUE TITLE
bgzip is dependent on deprecated failure crate

### ISSUE THREAD

**Issue by Ebedthan** [informationsea/bgzip-rs#1]
Hi @informationsea,

failure crate is deprecated and unmaintained as pointed out by [RUSTSEC](https://github.com/rust-lang-nursery/failure/pull/347). Can you please update the crate to rather use `anyhow` or `thiserror`? I can also fix that for you if you are too busy.

Waiting for your feedback.

**Comment by Ebedthan** [comment]
Here is a [PR](https://github.com/informationsea/bgzip-rs/pull/2) to fix this issue.

**Comment by informationsea** [comment]
Thank you. I merged your pull request and released as version 0.2.0.
