### ISSUE TITLE
'Prepare' println appears in production 

### ISSUE THREAD

**Issue by aaronmck** [informationsea/bgzip-rs#9]
Really nice crate!! I was playing around with some bgzip implementations and ran into your crate. It's really nice. I was getting some random 'Prepare' in my output stream, and I think (?) this is from an uncommented println making it into the crate. I see it's commented out in the source here. Thanks again!

**Comment by informationsea** [comment]
This problem was fixed in version 0.2.2.
Sorry for inconvenience.
